# Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
import numpy as np
from numpy import random
from scipy import stats

def statisticalSummary(array):
    if array.ndim == 1:
        print("Mitjana aritmètica =",np.mean(array))
        print("Mediana =", np.median(array))
        print("Moda =", stats.mode(array))      # Retorna el nombre moda i les vegades que es repeteix.
        print("Desviació estàndard =", np.std(array))
    else:
        print("* Error: L'array té més d'una dimensió.")

In [2]:
# Generació de matriu 1D
array = random.randint(100, size=(8))
print(array)
statisticalSummary(array)

[70 56  4 57 31 30 68 44]
Mitjana aritmètica = 45.0
Mediana = 50.0
Moda = ModeResult(mode=array([4]), count=array([1]))
Desviació estàndard = 20.982135258357285


In [3]:
# Generació de matriu 2D
array = random.randint(100, size=(3, 6))
print(array)
statisticalSummary(array)

[[16 61 67 93 91 73]
 [70 19 30 28 75 66]
 [42 81 28  6 62 88]]
* Error: L'array té més d'una dimensió.


# Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [4]:
import numpy as np

def createSquare(n):
    arraySquare = random.randint(100, size=(n, n))
    print(arraySquare)

In [5]:
n = random.randint(1, 6)
print(n)
createSquare(n)

4
[[47 44 99 25]
 [ 1 98 91 74]
 [37 59 29 25]
 [12 85 13 99]]


# Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [6]:
def sumForRowForColumn(array):
    arraySumRows = np.sum(array, axis=1)
    arraySumColumns = np.sum(array, axis=0)
    print("Les sumes per fila són ",arraySumRows)
    print("Les sumes per columna són ", arraySumColumns)

In [7]:
array = random.randint(10, size=(3, 5))
array

array([[7, 0, 7, 5, 4],
       [2, 1, 1, 5, 2],
       [8, 3, 3, 1, 3]])

In [8]:
sumForRowForColumn(array)

Les sumes per fila són  [23 11 18]
Les sumes per columna són  [17  4 11 11  9]
